[package]
distribution = "2201.13.0"
org = "ballerina"
name = "smb"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = [] # TODO: Add keywords
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerina-smb"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
