[package]
org = "ballerina"
name = "smb"
version = "0.1.0"
authors = ["Ballerina"]
keywords = ["smb", "file", "network shares"]
repository = "https://github.com/ballerina-platform/module-ballerina-smb"
# icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "com.hierynomus"
artifactId = "smbj"
version = "0.13.0"
path = "./lib/smbj-0.13.0.jar"

[[platform.java21.dependency]]
groupId = "com.hierynomus"
artifactId = "asn-one"
version = "0.6.0"
path = "./lib/asn-one-0.6.0.jar"

[[platform.java21.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "1.70"
path = "./lib/bcprov-jdk15on-1.70.jar"

[[platform.java21.dependency]]
groupId = "eu.agno3.jcifs"
artifactId = "jcifs-ng"
version = "2.1.7"
path = "./lib/jcifs-ng-2.1.7.jar"

[[platform.java21.dependency]]
groupId = "net.engio"
artifactId = "mbassador"
version = "1.3.2"
path = "./lib/mbassador-1.3.2.jar"

[[platform.java21.dependency]]
groupId = "org.slf4j"
artifactId = "slf4j-api"
version = "1.7.30"
path = "./lib/slf4j-api-1.7.30.jar"

[[platform.java21.dependency]]
groupId = "commons-io"
artifactId = "commons-io"
version = "2.18.0"
path = "./lib/commons-io-2.18.0.jar"

# [[platform.java21.dependency]]
# groupId = "org.apache.commons"
# artifactId = "commons-lang3"
# version = "3.18.0"
# path = "./lib/commons-lang3-3.18.0.jar"

[[platform.java21.dependency]]
groupId = "org.apache.commons"
artifactId = "commons-vfs2"
version = "2.9.0"
path = "./lib/commons-vfs2-2.9.0.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "smb-native"
version = "0.1.0"
path = "../native/build/libs/smb-native-0.1.0-SNAPSHOT.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.jsondata-native"
version = "1.1.3"
path = "./lib/data.jsondata-native-1.1.3.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.xmldata-native"
version = "1.5.2"
path = "./lib/data.xmldata-native-1.5.2.jar"

[[platform.java21.dependency]]
groupId = "io.ballerina.lib"
artifactId = "data.csv-native"
version = "0.9.0"
path = "./lib/data.csv-native-0.9.0.jar"
