[package]
distribution = "2201.13.0"
org = "ballerina"
name = "smb"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
# icon = "icon.png" # TODO: update icon.png
repository = "https://github.com/ballerina-platform/module-ballerina-smb"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
