[package]
org = "ballerina"
name = "sales_report"
version = "0.1.0"
distribution = "2201.12.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "smb"
repository = "local"
version = "0.1.0"
